

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: hortifruti-pratico-service
  data:
    mongodb:
      uri: mongodb+srv://lucianodepaula:1100#Mongo@cluster0.3ghsg.mongodb.net/?retryWrites=true&w=hortifruti_pratico
      database: hortifruti_pratico